#!/bin/bash

dotnet build
#dotnet run --project iasc-app $*

export IASC_VCS_MODE=local #git #local

SRC_DIR=samples/input-gce
if [[ ${IASC_VCS_MODE} == "git" ]]
then
  SRC_DIR=samples/wip/input
  mkdir -p ${SRC_DIR}
  rm -rf ${SRC_DIR}/*  
fi

WIP_DIR=samples/wip/output
TMP_DIR=samples/wip/temp

rm -rf ${WIP_DIR}/* ${TMP_DIR}/*

export IASC_SRC_DIR=${SRC_DIR}
export IASC_WIP_DIR=${WIP_DIR}
export IASC_TMP_DIR=${TMP_DIR}

export IASC_VCS_URL=https://github.com/its-software-services-devops/infra-devops.git
export IASC_VCS_REF=develop
export IASC_VCS_FOLDER=gce-rke-manager
export IASC_VAULT_SECRETS=gs://its-config-params/gcp-rke-demo-cluster/secrets.txt #samples/secrets/test-secrets.cfg

dotnet iasc-app/bin/Debug/net5.0/iasc-app.dll $*