#!/bin/bash

dotnet build
#dotnet run --project iasc-app $*

SUBSYSTEM=rke

WIP_DIR=/tmp/iasc-wip
SRC_DIR=/tmp/iasc-input

mkdir -p ${SRC_DIR}
rm -rf ${SRC_DIR}/* ${WIP_DIR}/*

export IASC_SRC_DIR=${SRC_DIR} #samples/input-${SUBSYSTEM}
export IASC_WIP_DIR=${WIP_DIR} #samples/wip/${SUBSYSTEM}

export IASC_VCS_MODE=git
export IASC_VCS_URL=https://github.com/its-software-services-devops/infra-devops.git
export IASC_VCS_REF=develop
export IASC_VCS_FOLDER=gce-rke-manager

dotnet iasc-app/bin/Debug/net5.0/iasc-app.dll $*