addons_include: []

services:
  kube-api:
    service_cluster_ip_range: 192.168.200.0/21
    service_node_port_range: 30000-32767
  kube-controller:
    cluster_cidr: 192.168.128.0/18
    service_cluster_ip_range: 192.168.200.0/21
  kubelet:
    cluster_dns_server: 192.168.200.10